apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stepik-solver-secret
  namespace: antlers
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: stepik-solver-secret
  data:
    - secretKey: postgres-password
      remoteRef:
        key: infra/services/stepik-solver
        property: db-password
    - secretKey: anthropic-api-key
      remoteRef:
        key: infra/services/stepik-solver
        property: anthropic-api-key
